'use strict';

var license = {
  AFL2: 'AFL 2.1',
  AFL3: 'AFL 3.0',
  AGPL3: 'AGPL 3.0',
  CCBY: 'CC 3.0 BY',
  CCBYND: 'CC 3.0 BY-ND',
  CCBYSA: 'CC 3.0 BY-SA',
  CCBYNC: 'CC 3.0 BY-NC',
  CCBYNDSA: 'CC 3.0 BY-ND-SA',
  CCBYNCSA: 'CC 3.0 BY-NC-SA',
  CCBYNCND: 'CC 3.0 BY-NC-ND',
  APL1: 'APL 1.0',
  ARTISTIC2: 'Artistic 2.0',
  Apache2: 'Apache 2.0',
  Apache: 'Apache',
  BEER: 'Beerware',
  BSD2: 'BSD 2-Clause',
  BSD3: 'BSD 3-Clause',
  BSD: 'BSD 4-Clause',
  BSL1: 'BSL 1.0',
  CDDL1: 'CDDL 1.0',
  GPL2: 'GPL 2.0',
  GPL3: 'GPL 3.0',
  GPL: 'GPL',
  ISC: 'ISC',
  JSON: 'JSON.org',
  LGPL2: 'LGPL 2.1',
  LGPL3: 'LGPL 3.0',
  LGPL: 'LGPL',
  MIT: 'MIT',
  MPL2: 'MPL 2.0',
  MPL: 'MPL 1.0',
  NASA1: 'NASA 1.3',
  PROPRIETARY: 'Proprietary',
  PSF: 'Python 2.0',
  PUBLIC: 'Public Domain',
  UNLICENSE: 'Unlicense',
  WTFPL: 'WTFPL',
  ZLIB: 'zlib/libpng',
};

//
// Map commonly used terms to a normal license value as you can usually specify
// your license type in so many ways. By mapping this, we can create a more
// readable format for each license type.
//
module.exports = [
  { key: '"BSD"', value: license.BSD },
  { key: '(Un)license', value: license.UNLICENSE },
  { key: '2-clause BSD', value: license.BSD2 },
  { key: '3-clause BSD', value: license.BSD3 },
  { key: 'AFLv2.1', value: license.AFL2 },
  { key: 'AGPL 3', value: license.AGPL3 },
  { key: 'AGPL 3.0', value: license.AGPL3 },
  { key: 'AGPL v3', value: license.AGPL3 },
  { key: 'AGPL', value: license.AGPL3 },
  { key: 'AGPL-3', value: license.AGPL3 },
  { key: 'AGPL-3.0', value: license.AGPL3 },
  { key: 'AGPL3', value: license.AGPL3 },
  { key: 'AGPLv3', value: license.AGPL3 },
  { key: 'AGPLv3+', value: license.AGPL3 },
  { key: 'ALv2', value: license.AFL2 },
  { key: 'APACHE 2.0', value: license.Apache2 },
  { key: 'APACHE V2.0', value: license.Apache2 },
  { key: 'APACHE', value: license.Apache },
  { key: 'APACHE-2.0', value: license.Apache2 },
  { key: 'APACHE2', value: license.Apache2 },
  { key: 'APACHE2.0', value: license.Apache2 },
  { key: 'APACHE2_0', value: license.Apache2 },
  { key: 'APACHEv2', value: license.Apache2 },
  { key: 'APL', value: license.APL1 },
  { key: 'APLv2', value: license.Apache2 },
  { key: 'ARTISTIC 2.0', value: license.ARTISTIC2 },
  { key: 'Affero General Public License v3', value: license.AGPL3 },
  { key: 'Apache (2.0)', value: license.Apache2 },
  { key: 'Apache 2 License', value: license.Apache2 },
  { key: 'Apache 2', value: license.Apache2 },
  { key: 'Apache 2.0', value: license.Apache2 },
  { key: 'Apache License 2', value: license.Apache2 },
  { key: 'Apache License 2.0', value: license.Apache2 },
  { key: 'Apache License Version 2', value: license.Apache2 },
  { key: 'Apache License Version 2.0', value: license.Apache2 },
  { key: 'Apache License v2', value: license.Apache2 },
  { key: 'Apache License v2.0', value: license.Apache2 },
  { key: 'Apache License version 2.0', value: license.Apache2 },
  { key: 'Apache License', value: license.Apache },
  { key: 'Apache License, Version 2.0', value: license.Apache2 },
  { key: 'Apache License, Version 2.0, http://www.apache.org/licenses/LICENSE-2.0', value: license.Apache2 },
  { key: 'Apache Public License (version 2)', value: license.Apache2  },
  { key: 'Apache Public License v2', value: license.Apache2 },
  { key: 'Apache Public License, Version 2', value: license.Apache2 },
  { key: 'Apache Software License 2.0', value: license.Apache2 },
  { key: 'Apache V2', value: license.Apache2 },
  { key: 'Apache V2.0', value: license.Apache2 },
  { key: 'Apache v2 License', value: license.Apache2 },
  { key: 'Apache v2 license', value: license.Apache },
  { key: 'Apache v2', value: license.Apache2 },
  { key: 'Apache v2.0', value: license.Apache2 },
  { key: 'Apache version 2.0', value: license.Apache2 },
  { key: 'Apache', value: license.Apache },
  { key: 'Apache, Version 2.0', value: license.Apache2 },
  { key: 'Apache-2', value: license.Apache2 },
  { key: 'Apache-2.0', value: license.Apache2 },
  { key: 'Apache-V2', value: license.Apache2 },
  { key: 'Apache2', value: license.Apache2 },
  { key: 'Apache2.0', value: license.Apache2 },
  { key: 'Appcelerator Proprietary and Confidential', value: license.PROPRIETARY },
  { key: 'Artistic-2.0', value: license.ARTISTIC2 },
  { key: 'Attribution-NonCommercial 2.5 Generic (CC BY-NC 2.5)', value: 1 },
  { key: 'Attribution-ShareAlike 3.0 Unported', value: 1 },
  { key: 'BOOST', value: license.BSL1 },
  { key: 'BSD 2 Clause', value: license.BSD2 },
  { key: 'BSD 2-Clause License', value: license.BSD2 },
  { key: 'BSD 2-Clause license', value: license.BSD2 },
  { key: 'BSD 2-Clause', value: license.BSD2 },
  { key: 'BSD 2-clause license', value: license.BSD2 },
  { key: 'BSD 3-Clause License', value: license.BSD3 },
  { key: 'BSD 3-Clause', value: license.BSD3 },
  { key: 'BSD License', value: license.BSD },
  { key: 'BSD New', value: license.BSD3 },
  { key: 'BSD', value: license.BSD },
  { key: 'BSD-2-Clause', value: license.BSD2 },
  { key: 'BSD-3', value: license.BSD3 },
  { key: 'BSD-3-Clause', value: license.BSD3 },
  { key: 'BSD-new', value: license.BSD3 },
  { key: 'BSD2', value: license.BSD2 },
  { key: 'BSD3', value: license.BSD3 },
  { key: 'BeerWare', value: license.BEER },
  { key: 'Beerware', value: license.BEER },
  { key: 'CC BY-NC 3.0', value: license.CCBYNC },
  { key: 'CC BY-NC', value: license.CCBYNC },
  { key: 'CC BY-NC-SA', value: license.CCBYNCSA },
  { key: 'CC BY-SA 3.0', value: license.CCBYSA },
  { key: 'CC BY-SA v3.0', value: license.CCBYSA },
  { key: 'CC', value: license.CCBY },
  { key: 'CC-0', value: license.CCBY },
  { key: 'CC-BY 2.0', value: license.CCBY },
  { key: 'CC-BY-NC-SA', value: license.CCBYNCSA },
  { key: 'CC-BY-SA', value: license.CCBYSA },
  { key: 'CC-By-SA 3.0', value: license.CCBYSA },
  { key: 'CC-SA-BY-3.0', value: license.CCBYSA },
  { key: 'CC-by-SA', value: license.CCBYSA },
  { key: 'CC0 1.0', value: license.CCBY },
  { key: 'CC3', value: license.CCBY },
  { key: 'CC_by_3.0', value: license.CCBY },
  { key: 'CDDL', value: license.CDDL1 },
  { key: 'Closed Source', value: license.PROPRIETARY },
  { key: 'Copyrighted - CC BY-NC-ND', value: license.CCBYNCND },
  { key: 'Creative Commons - Attribution 3.0', value: license.CCBY },
  { key: 'Creative Commons 3.0', value: license.CCBY },
  { key: 'Creative Commons Attribution 3.0 Unported License', value: license.CCBY },
  { key: 'Creative Commons Attribution', value: license.CCBY },
  { key: 'Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)', value: license.CCBYNCSA },
  { key: 'Creative Commons Attribution-ShareAlike 3.0 Unported', value: license.CCBYSA },
  { key: 'Creative Commons Attribution-ShareAlike 3.0', value: license.CCBYSA },
  { key: 'Creative Commons BY-NC-SA License 3.0', value: license.CCBYNCSA },
  { key: 'Creative Commons Legal Code Attribution-NonCommercial-NoDerivs 3.0', value: license.CCBYNCND },
  { key: 'Creative Commons License 2.5', value: license.CCBY },
  { key: 'Creative Commons attribution and share-alike license', value: license.CCBYSA },
  { key: 'Creative Commons', value: license.CCBY },
  { key: 'DO-WHAT-YOU-WANT', value: license.WTFPL },
  { key: 'DWTFYW', value: license.WTFPL },
  { key: 'Do What the Fuck You Want to Public License', value: license.WTFPL },
  { key: 'Doug Crockford\'s license that allows this module to be used for Good but not for Evil', value: license.JSON },
  { key: 'Free as in Hugs Licence', value: license.PUBLIC },
  { key: 'Free as in Hugs License', value: license.PUBLIC },
  { key: 'Free as in Hugs', value: license.PUBLIC },
  { key: 'Free', value: license.PUBLIC },
  { key: 'FreeBSD', value: license.BSD2 },
  { key: 'GLP v.3', value: license.GPL3 },
  { key: 'GLP v2.0', value: license.GPL2 },
  { key: 'GLP', value: license.GPL },
  { key: 'GNU AFFERO GENERAL PUBLIC LICENSE', value: license.AGPL3 },
  { key: 'GNU AGPL v3.0', value: license.AGPL3 },
  { key: 'GNU Affero General Public License', value: license.AGPL3 },
  { key: 'GNU GENERAL PUBLIC LICENSE', value: license.GPL },
  { key: 'GNU GPL 2', value: license.GPL2 },
  { key: 'GNU GPL V3', value: license.GPL3 },
  { key: 'GNU GPL v3', value: license.GPL3 },
  { key: 'GNU GPL', value: license.GPL },
  { key: 'GNU GPLv3', value: license.GPL3 },
  { key: 'GNU General Public License', value: license.GPL },
  { key: 'GNU LGPL v3.0', value: license.LGPL3 },
  { key: 'GNU LGPL', value: license.LGPL },
  { key: 'GNU Library General Public License', value: license.LGPL },
  { key: 'GNU v3', value: license.GPL3 },
  { key: 'GNU', value: license.GPL },
  { key: 'GNU-GPL-2', value: license.GPL2 },
  { key: 'GPL 2', value: license.GPL2 },
  { key: 'GPL 2.0', value: license.GPL2 },
  { key: 'GPL 3', value: license.GPL3 },
  { key: 'GPL 3.0', value: license.GPL3 },
  { key: 'GPL Version 3', value: license.GPL3 },
  { key: 'GPL v2', value: license.GPL2 },
  { key: 'GPL v2+', value: license.GPL2 },
  { key: 'GPL v3', value: license.GPL3 },
  { key: 'GPL v3.0', value: license.GPL3 },
  { key: 'GPL', value: license.GPL },
  { key: 'GPL-2', value: license.GPL2 },
  { key: 'GPL-2.0', value: license.GPL2 },
  { key: 'GPL-3', value: license.GPL3 },
  { key: 'GPL-3.0', value: license.GPL3 },
  { key: 'GPL-v2', value: license.GPL2 },
  { key: 'GPL2', value: license.GPL2 },
  { key: 'GPL3', value: license.GPL3 },
  { key: 'GPLv2 (or later)', value: license.GPL3 },
  { key: 'GPLv2', value: license.GPL2 },
  { key: 'GPLv3', value: license.GPL3 },
  { key: 'GPOL', value: license.GPL },
  { key: 'Google-BSD', value: license.BSD },
  { key: 'ISC (http://www.isc.org/software/license)', value: license.ISC },
  { key: 'ISC License', value: license.ISC },
  { key: 'ISC', value: license.ISC },
  { key: 'JSON', value: license.JSON },
  { key: 'LGP', value: license.LGPL },
  { key: 'LGPL 2.1', value: license.LGPL2 },
  { key: 'LGPL 2.1+', value: license.LGPL2 },
  { key: 'LGPL 3', value: license.LGPL3 },
  { key: 'LGPL 3.0', value: license.LGPL3 },
  { key: 'LGPL License', value: license.LGPL },
  { key: 'LGPL V3', value: license.LGPL3 },
  { key: 'LGPL v3', value: license.LGPL3 },
  { key: 'LGPL', value: license.LGPL },
  { key: 'LGPL+', value: license.LGPL },
  { key: 'LGPL-2', value: license.LGPL2 },
  { key: 'LGPL-3', value: license.LGPL3 },
  { key: 'LGPL-3.0', value: license.LGPL3 },
  { key: 'LGPL3', value: license.LGPL3 },
  { key: 'LGPL3.0', value: license.LGPL3 },
  { key: 'LGPLv2.1', value: license.GPL2 },
  { key: 'LGPLv2.1+', value: license.LGPL2 },
  { key: 'LGPLv21', value: license.LGPL2 },
  { key: 'LGPLv3', value: license.LGPL3 },
  { key: 'LGPLv3+', value: license.LGPL3 },
  { key: 'LGPLv3.0', value: license.LGPL3 },
  { key: 'MIT ', value: license.MIT },
  { key: 'MIT (http://mootools.net/license.txt)', value: license.MIT },
  { key: 'MIT <http://opensource.org/licenses/MIT>', value: license.MIT },
  { key: 'MIT Licence', value: license.MIT },
  { key: 'MIT License (see License)', value: license.MIT },
  { key: 'MIT License (see Readme)', value: license.MIT },
  { key: 'MIT License', value: license.MIT },
  { key: 'MIT license', value: license.MIT },
  { key: 'MIT', value: license.MIT },
  { key: 'MIT-License', value: license.MIT },
  { key: 'MIT/X', value: license.MIT },
  { key: 'MIT/X11', value: license.MIT },
  { key: 'MPL 1.1', value: license.MPL },
  { key: 'MPL 2.0', value: license.MPL2 },
  { key: 'MPL v2.0', value: license.MPL2 },
  { key: 'MPL', value: license.MPL },
  { key: 'MPL-2', value: license.MPL2 },
  { key: 'MPL-2.0', value: license.MPL2 },
  { key: 'MPL/2.0', value: license.MPL2 },
  { key: 'MPL2', value: license.MPL2 },
  { key: 'MPL2.0', value: license.MPL2 },
  { key: 'MPLv2', value: license.MPL2 },
  { key: 'MPLv2.0', value: license.MPL2 },
  { key: 'MTI', value: license.MIT },
  { key: 'Mit', value: license.MIT },
  { key: 'Modified MIT / BSD', value: license.BSD },
  { key: 'Mozilla Public License 2.0', value: license.MPL2 },
  { key: 'Mozilla Public License Version 2.0', value: license.MPL2 },
  { key: 'Mozilla Public License', value: license.MPL },
  { key: 'NASA-1.3', value: license.NASA1 },
  { key: 'NEW BSD', value: license.BSD3 },
  { key: 'New BSD License', value: license.BSD3 },
  { key: 'New BSD', value: license.BSD3 },
  { key: 'New-BSD', value: license.BSD3 },
  { key: 'NewBSD', value: license.BSD3 },
  { key: 'Open Source- GPL', value: license.GPL },
  { key: 'PROPRIETARY', value: license.PROPRIETARY },
  { key: 'PSF', value: license.PSF },
  { key: 'PUBLIC DOMAIN (UNLICENSED)', value: license.PUBLIC },
  { key: 'PUBLIC LICENSE', value: license.PUBLIC },
  { key: 'Private', value: license.PROPRIETARY },
  { key: 'Proprietary', value: license.PROPRIETARY },
  { key: 'Public Domain', value: license.PUBLIC },
  { key: 'Public domain', value: license.PUBLIC },
  { key: 'Simplified BSD (see License)', value: license.BSD2 },
  { key: 'Simplified BSD License', value: license.BSD2 },
  { key: 'Simplified BSD-3', value: license.BSD3 },
  { key: 'The MIT Licence', value: license.MIT },
  { key: 'The MIT License (MIT)', value: license.MIT },
  { key: 'The MIT License', value: license.MIT },
  { key: 'The Software shall be used for Good, not Evil. (see LICENSE)', value: license.JSON },
  { key: 'To Use: WTFPL, To Contribute: Dojo CLA', value: license.WTFPL },
  { key: 'UNLICENSE', value: license.UNLICENSE },
  { key: 'UNLICENSED', value: license.UNLICENSE },
  { key: 'Unlicense <http://unlicense.org/>', value: license.UNLICENSE },
  { key: 'Unlicense', value: license.UNLICENSE },
  { key: 'WTFPL', value: license.WTFPL },
  { key: 'WTFPLv2', value: license.WTFPL },
  { key: 'X11 License', value: license.MIT },
  { key: 'X11', value: license.MIT },
  { key: 'X11-style', value: license.MIT },
  { key: 'ZLIB', value: license.ZLIB },
  { key: 'apache 2', value: license.Apache2 },
  { key: 'apache 2.0', value: license.Apache2 },
  { key: 'apache2 actually', value: license.Apache2 },
  { key: 'apache2', value: license.Apache2 },
  { key: 'apachev2', value: license.Apache2 },
  { key: 'bsd', value: license.BSD },
  { key: 'cc-by-sa', value: license.CCBYSA },
  { key: 'free', value: license.PUBLIC },
  { key: 'freeBSD', value: license.BSD3 },
  { key: 'gnu', value: license.GPL },
  { key: 'gpl-3.0', value: license.GPL3 },
  { key: 'gpl-v3.0', value: license.GPL3 },
  { key: 'http://creativecommons.org/licenses/by/3.0/', value: license.CCBY },
  { key: 'http://opensource.org/licenses/MIT', value: license.MIT },
  { key: 'http://unlicense.org/', value: license.UNLICENSE },
  { key: 'http://wtfpl.org', value: license.WTFPL },
  { key: 'http://wtfpl.org/', value: license.WTFPL },
  { key: 'http://www.apache.org/licenses/LICENSE-2.0', value: license.Apache2 },
  { key: 'http://www.apache.org/licenses/LICENSE-2.0.txt', value: license.Apache2 },
  { key: 'mit', value: license.MIT },
  { key: 'mti', value: license.MIT },
  { key: 'my own', value: license.PROPRIETARY },
  { key: 'new BSD', value: license.BSD3 },
  { key: 'no', value: license.PUBLIC },
  { key: 'none', value: license.PUBLIC },
  { key: 'propriatry', value: license.PROPRIETARY },
  { key: 'proprietary', value: license.PROPRIETARY },
  { key: 'public domain', value: license.PUBLIC },
  { key: 'unlicense', value: license.UNLICENSE },
  { key: 'unlicensed', value: license.UNLICENSE },
  { key: 'wtfpl', value: license.WTFPL },
  { key: 'zlib', value: license.ZLIB },
  { key: 'zlib/libpng', value: license.ZLIB },
];

//
// Ensure that we didn't create any undefined references.
//
module.exports.forEach(function check(license) {
  if (!license.value) throw new Error('Invalid reference for:'+ license.key);
});
